# Generated by Django 5.0.3 on 2024-03-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
