# Generated by Django 5.0.4 on 2024-04-12 14:14
from django.db import migrations, models


class Migration(migrations.Migration):
    """ """

    dependencies = [
        ("forms", "0003_useranswers_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forms",
            name="description",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
