# Generated by Django 5.0.4 on 2024-04-13 16:21

from django.db import migrations


class Migration(migrations.Migration):
    """ """

    dependencies = [
        ("forms", "0009_remove_questions_only_one_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="question_type",
            new_name="type",
        ),
    ]
