# Generated by Django 5.0.4 on 2024-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_alter_questions_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="required",
            field=models.BooleanField(default=False),
        ),
    ]
