# Generated by Django 5.0.4 on 2024-04-13 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_useranswers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='text_choice',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.choices'),
        ),
    ]
