# Generated by Django 5.0.4 on 2024-04-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_useranswers_text_choice_alter_useranswers_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='session_id',
            field=models.UUIDField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
