services:
  - type: web
    plan: free
    name: LibreForms
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn 'LibreForms.asgi:application' --host=0.0.0.0 --port=8000"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: POSTGRES_URL
        sync: false